### PR TITLE
Adding funcions

### LINKED ISSUE #11: Complete the commented functions
Go to constants submodule in src>>fermulerpy and complete commented functions in file useful_series.py

### PR DESCRIPTION
**Pull request by sumit-158**
closes #11 
I have completed some of functions

### CODE REVIEW

**Comment by sumit-158** [comment]
Hey, @MAG-BOSS Is there any issue in this PR , why its not merged yet?

**Comment by MAG-BOSS** [comment]
@sumit-158 give some time for review

**Review by MAG-BOSS — CHANGES_REQUESTED** [review]
@sumit-158 , your code need some changes as described below:
1. In latest code, you will see NotImplementedError is replaced with ValueError. So, do the required replacements.
2. Some of the functions can be optimised further using dynamic programming or memoization
3. Also, don't commit spelling mistakes in commit messages atleast!!

**Comment by MAG-BOSS** [comment]
@sumit-158 are you still working on it?

**Pull request closed without merging**
